### ISSUE TITLE
"BELT_FAIL" when using mining bot. 

### ISSUE THREAD

**Issue by jazminegames** [Katodiy/nurgling#2]
When I use the mining bot with (0.032a) it often cant drink from the waterskins in the belt. The fix ive found is to click the belt to pick it up off the character then put it back on. If this isnt done in time, the BELT_FAIL error comes up and the mining bot stalls eventually cancelling out. 

My belt always stays open, but ive tried to recreate the bug without having the belt open and it happens. 

Thank you for all ur hard work

**Comment by Katodiy** [comment]
Hello, this issue was resolved in commit b5ac549. The problem will be fixed in the next release.
